const mongoose = require("mongoose");
const db = require("../models");

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost/fightbookDB");

const userSeed = [
  {
    firstName: "Daniel",
    lastName: "Kari",
    address: "1507 Bulevardi",
    city: "Juupajoki",
    state: "CT",
    zip: "87929",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "daniel.kari@example.com",
    gymName: "",
    licNum: "",
    userName: "yellowbird175",
    password: "happy123",
    role: "User",
    title: "",
    phoneNumber: "58128482",
    picture: "https://randomuser.me/api/portraits/med/men/87.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/87.jpg",
  },
  {
    firstName: "Elias",
    lastName: "Olsen",
    address: "3186 Søndre Landevej",
    city: "Juupajoki",
    state: "CT",
    zip: "87929",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "elias.olsen@example.com",
    gymName: "",
    licNum: "",
    userName: "orangecat233",
    password: "norway",
    role: "User",
    title: "",
    phoneNumber: "58128482",
    picture: "https://randomuser.me/api/portraits/med/men/87.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/87.jpg",
  },
  {
    firstName: "Silas",
    lastName: "Jensen",
    address: "3857 Skærbækvej",
    city: "Pandrup",
    state: "CT",
    zip: "43808",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "silas.jensen@example.com",
    gymName: "Silas Gym",
    licNum: "23e6c46d",
    userName: "tinybear818",
    password: "xxxx",
    role: "Couch",
    title: "",
    phoneNumber: "69357719",
    picture: "https://randomuser.me/api/portraits/med/men/94.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/94.jpg",
  },
  {
    firstName: "Daniel",
    lastName: "Saari",
    address: "562 Otavalankatu",
    city: "Hollola",
    state: "CT",
    zip: "49798",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "daniel.saari@example.com",
    gymName: "Saari Gym",
    licNum: "1cfd0c15",
    userName: "sadwolf228",
    password: "peaches",
    role: "Couch",
    title: "",
    phoneNumber: "07-721-755",
    picture: "https://randomuser.me/api/portraits/med/men/45.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/45.jpg",
  },
  {
    firstName: "Felipe",
    lastName: "Bravo",
    address: "9398 Ronda de Toledo",
    city: "Alcobendas",
    state: "CT",
    zip: "64136",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "felipe.bravo@example.com",
    gymName: "Bravo Gym",
    licNum: "08177674",
    userName: "orangedog895",
    password: "rage",
    role: "Couch",
    title: "",
    phoneNumber: "907-536-795",
    picture: "https://randomuser.me/api/portraits/med/men/76.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/76.jpg",
  },
  {
    firstName: "Nikolaus",
    lastName: "Gerard",
    address: "3876 Cours Charlemagne",
    city: "Saulcy",
    state: "CT",
    zip: "3749",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "nikolaus.gerard@example.com",
    gymName: "Bravo Gym",
    licNum: "193b8551",
    userName: "organictiger963",
    password: "fastball",
    role: "Couch",
    title: "",
    phoneNumber: "0767330209",
    picture: "https://randomuser.me/api/portraits/med/men/70.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/70.jpg",
  },
  {
    firstName: "Tristan",
    lastName: "Møller",
    address: "2480 Grejsdalsvej",
    city: "København N",
    state: "CT",
    zip: "33981",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "tristan.moller@example.com",
    gymName: "Tristan Gym",
    licNum: "9be8e6a7",
    userName: "greencat294",
    password: "1999",
    role: "Couch",
    title: "",
    phoneNumber: "003321",
    picture: "https://randomuser.me/api/portraits/med/men/5.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/5.jpg",
  },
  {
    firstName: "Ryan",
    lastName: "Lévesque",
    address: "1705 Simcoe St",
    city: "Dorchester",
    state: "CT",
    zip: "00000",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "ryan.levesque@example.com",
    gymName: "Small Fish Gym",
    licNum: "b0cf859",
    userName: "smallfish856",
    password: "flames",
    role: "Couch",
    title: "",
    phoneNumber: "275-281-3329",
    picture: "https://randomuser.me/api/portraits/med/men/79.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/79.jpg",
  },
  {
    firstName: "Riley",
    lastName: "Singh",
    address: "1479 Pakowhai Road",
    city: "Timaru",
    state: "CT",
    zip: "44457",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "riley.singh@example.com",
    gymName: "Timaru Gym",
    licNum: "e688925e",
    userName: "smallwolf956",
    password: "sammie",
    role: "Couch",
    title: "",
    phoneNumber: "(547)-466-3449",
    picture: "https://randomuser.me/api/portraits/med/men/16.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/16.jpg",
  },
  {
    firstName: "Gaston",
    lastName: "Knoppert",
    address: "2874 Graaf Geraldlaan",
    city: "Delfgauw",
    state: "CT",
    zip: "38328",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "gaston.knoppert@example.com",
    gymName: "Black Gym",
    licNum: "5eb778a3",
    userName: "blackcat270",
    password: "carlton",
    role: "Couch",
    title: "",
    phoneNumber: "(201)-060-7590",
    picture: "https://randomuser.me/api/portraits/med/men/36.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/36.jpg",
  },
  {
    firstName: "Joshua",
    lastName: "Nguyen",
    address: "6396 Dane St",
    city: "Rancho Cucamonga",
    state: "CT",
    zip: "18832",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "joshua.nguyen@example.com",
    gymName: "Rancho Gym",
    licNum: "95c4dc9c",
    userName: "ticklishmeercat932",
    password: "reds",
    role: "Couch",
    title: "",
    phoneNumber: "(477)-961-0773",
    picture: "https://randomuser.me/api/portraits/med/men/46.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/46.jpg",
  },
  {
    firstName: "Willy",
    lastName: "Gärtner",
    address: "9903 Wiesenweg",
    city: "Heppenheim (Bergstraße)",
    state: "CT",
    zip: "16390",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "willy.gartner@example.com",
    gymName: "White Rabbit Gym",
    licNum: "8dda92ac",
    userName: "whiterabbit465",
    password: "busted",
    role: "Couch",
    title: "",
    phoneNumber: "0514-7873234",
    picture: "https://randomuser.me/api/portraits/med/men/14.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/14.jpg",
  },
  {
    firstName: "Dominik",
    lastName: "Bernard",
    address: "4024 Rue de L'Abbé-Patureau",
    city: "Beckenried",
    state: "CT",
    zip: "8693",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "dominik.bernard@example.com",
    gymName: "",
    licNum: "",
    userName: "goldenwolf494",
    password: "iforgot",
    role: "User",
    title: "",
    phoneNumber: "077 103 72 75",
    picture: "https://randomuser.me/api/portraits/med/men/26.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/26.jpg",
  },
  {
    firstName: "Eemeli",
    lastName: "Lepisto",
    address: "2630 Pirkankatu",
    city: "Teuva",
    state: "CT",
    zip: "91422",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "eemeli.lepisto@example.com",
    gymName: "",
    licNum: "",
    userName: "crazyelephant112",
    password: "magneto",
    role: "User",
    title: "",
    phoneNumber: "07-009-221",
    picture: "https://randomuser.me/api/portraits/med/men/92.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/92.jpg",
  },
  {
    firstName: "Santelmo",
    lastName: "Aragão",
    address: "5648 Rua Santa Luzia ",
    city: "Francisco Morato",
    state: "CT",
    zip: "80667",
    division: "Heavyweight",
    boxerHeight: 1.54,
    boxerReach: 52.1,
    boxerWins: 3,
    boxerLoses: 0,
    couchName: "Felipe Bravo",
    email: "santelmo.aragao@example.com",
    gymName: "Bravo Gym",
    licNum: "aaa2b117",
    userName: "greenkoala923",
    password: "watson",
    role: "Boxer",
    title: "none",
    phoneNumber: "(99) 0318-6399",
    picture: "https://randomuser.me/api/portraits/med/men/16.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/16.jpg",
  },
  {
    firstName: "Julian",
    lastName: "Vidal",
    address: "4559 Boulevard de la Duchère",
    city: "Brest",
    state: "CT",
    zip: "50201",
    division: "Heavyweight",
    boxerHeight: 1.62,
    boxerReach: 55.1,
    boxerWins: 34,
    boxerLoses: 5,
    couchName: "Felipe Bravo",
    email: "julian.vidal@example.com",
    gymName: "Bravo Gym",
    licNum: "f1e1d5a4",
    userName: "tinymeercat186",
    password: "zhua",
    role: "Boxer",
    title: "Heavyweight Champion",
    phoneNumber: "01-06-61-65-86",
    picture: "https://randomuser.me/api/portraits/med/men/69.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/69.jpg",
  },
  {
    firstName: "Malthe",
    lastName: "Rasmussen",
    address: "9024 Gammel Landevej",
    city: "Øster Assels",
    state: "CT",
    zip: "15730",
    division: "Heavyweight",
    boxerHeight: 1.59,
    boxerReach: 59.2,
    boxerWins: 22,
    boxerLoses: 1,
    couchName: "Felipe Bravo",
    email: "malthe.rasmussen@example.com",
    gymName: "Bravo Gym",
    licNum: "4e2ec6b9",
    userName: "silverfrog312",
    password: "boating",
    role: "Boxer",
    title: "none",
    phoneNumber: "76900189",
    picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/34.jpg",
  },
  {
    firstName: "Theodore",
    lastName: "Lowe",
    address: "3477 Hogan St",
    city: "Hobart",
    state: "CT",
    zip: "8236",
    division: "Heavyweight",
    boxerHeight: 1.86,
    boxerReach: 62.1,
    boxerWins: 13,
    boxerLoses: 0,
    couchName: "Felipe Bravo",
    email: "theodore.lowe@example.com",
    gymName: "Bravo Gym",
    licNum: "1df2b444",
    userName: "tinybird310",
    password: "fischer",
    role: "Boxer",
    title: "none",
    phoneNumber: "02-6677-7329",
    picture: "https://randomuser.me/api/portraits/med/men/62.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/62.jpg",
  },
  {
    firstName: "Ritthy",
    lastName: "Martinez",
    address: "840 The Drive",
    city: "Truro",
    state: "CT",
    zip: "00000",
    division: "Heavyweight",
    boxerHeight: 1.84,
    boxerReach: 60.5,
    boxerWins: 22,
    boxerLoses: 6,
    couchName: "Felipe Bravo",
    email: "ritthy.martinez@example.com",
    gymName: "Bravo Gym",
    licNum: "f1c7a316",
    userName: "ticklishfrog565",
    password: "david1",
    role: "Boxer",
    title: "Heavyweight Champion",
    phoneNumber: "02-6677-7329",
    picture: "https://randomuser.me/api/portraits/med/men/62.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/62.jpg",
  },
  {
    firstName: "Nihal",
    lastName: "Akman",
    address: "8022 Istikl",
    city: "Truro",
    state: "CT",
    zip: "00000",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "nihal.akman@example.com",
    gymName: "",
    licNum: "",
    userName: "organickoala193",
    password: "candy",
    role: "User",
    title: "",
    phoneNumber: "(250)-368-2548",
    picture: "https://randomuser.me/api/portraits/med/men/85.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/85.jpg",
  },
  {
    firstName: "Isar",
    lastName: "Van der Meijden",
    address: "2361 Groep Meelhuysenstraat",
    city: "Buren Fr",
    state: "CT",
    zip: "63652",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "isar.vandermeijden@example.com",
    gymName: "",
    licNum: "",
    userName: "ticklishrabbit923",
    password: "root",
    role: "User",
    title: "",
    phoneNumber: "(966)-047-3000",
    picture: "https://randomuser.me/api/portraits/med/men/70.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/70.jpg",
  },
  {
    firstName: "Javier",
    lastName: "Lozano",
    address: "4304 Calle de Bravo Murillo",
    city: "Alcalá de Henares",
    state: "CT",
    zip: "86837",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "javier.lozano@example.com",
    gymName: "",
    licNum: "",
    userName: "redpeacock150",
    password: "kirby",
    role: "User",
    title: "",
    phoneNumber: "916-154-290",
    picture: "https://randomuser.me/api/portraits/med/men/68.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/68.jpg",
  },
  {
    firstName: "Billy",
    lastName: "Soto",
    address: "530 Mockingbird Ln",
    city: "Shiloh",
    state: "CT",
    zip: "56912",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "billy.soto@example.com",
    gymName: "",
    licNum: "c6256693",
    userName: "greenkoala430",
    password: "spud",
    role: "ComOfi",
    title: "",
    phoneNumber: "(739)-131-4101",
    picture: "https://randomuser.me/api/portraits/med/men/93.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
  },
  {
    firstName: "آرش",
    lastName: "سهيلي راد",
    address: "2837 استاد نجات‌اللهی",
    city: "دزفول",
    state: "CT",
    zip: "11986",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "arsh.shylyrd@example.com",
    gymName: "",
    licNum: "d2c53145",
    userName: "redwolf371",
    password: "ophelia",
    role: "ComOfi",
    title: "",
    phoneNumber: "006-61644410",
    picture: "https://randomuser.me/api/portraits/med/men/7.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/7.jpg",
  },
  {
    firstName: "Edmund",
    lastName: "Hem",
    address: "495 Morells vei",
    city: "Fjellstad",
    state: "CT",
    zip: "0167",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "edmund.hem@example.com",
    gymName: "",
    licNum: "673e2f11",
    userName: "tinygorilla997",
    password: "000000",
    role: "ComOfi",
    title: "",
    phoneNumber: "53783482",
    picture: "https://randomuser.me/api/portraits/med/men/62.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/62.jpg",
  },
  {
    firstName: "Vinício",
    lastName: "de Souza",
    address: "3061 Rua São José ",
    city: "Balneário Camboriú",
    state: "CT",
    zip: "53239",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "vinicio.desouza@example.com",
    gymName: "",
    licNum: "985f6c28",
    userName: "organicdog388",
    password: "juicy",
    role: "ComOfi",
    title: "",
    phoneNumber: "(87) 3806-4745",
    picture: "https://randomuser.me/api/portraits/med/men/57.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/57.jpg",
  },
  {
    firstName: "Topias",
    lastName: "Koivisto",
    address: "410 Korkeavuorenkatu",
    city: "Eckerö",
    state: "CT",
    zip: "59167",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "topias.koivisto@example.com",
    gymName: "",
    licNum: "8bc82366",
    userName: "sadbird692",
    password: "davidson",
    role: "ComOfi",
    title: "",
    phoneNumber: "03-383-253",
    picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/34.jpg",
  },
  {
    firstName: "Francis",
    lastName: "Spencer",
    address: "7152 George Street",
    city: "Salisbury",
    state: "CT",
    zip: "BM1J 2SL",
    division: "Light heavyweight",
    boxerHeight: 1.41,
    boxerReach: 53.2,
    boxerWins: 27,
    boxerLoses: 1,
    couchName: "Felipe Bravo",
    email: "francis.spencer@example.com",
    gymName: "Bravo Gym",
    licNum: "23b3464f",
    userName: "ticklishmouse287",
    password: "1966",
    role: "Boxer",
    title: "none",
    phoneNumber: "024 4741 1079",
    picture: "https://randomuser.me/api/portraits/med/men/17.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/17.jpg",
  },
  {
    firstName: "Ramon",
    lastName: "Castro",
    address: "3880 Calle del Arenal",
    city: "Lorca",
    state: "CT",
    zip: "12001",
    division: "Light heavyweight",
    boxerHeight: 1.6,
    boxerReach: 68.2,
    boxerWins: 25,
    boxerLoses: 9,
    couchName: "Felipe Bravo",
    email: "ramon.castro@example.com",
    gymName: "Bravo Gym",
    licNum: "923d301c",
    userName: "silvermouse144",
    password: "aaron",
    role: "Boxer",
    title: "none",
    phoneNumber: "933-347-428",
    picture: "https://randomuser.me/api/portraits/med/men/72.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/72.jpg",
  },
  {
    firstName: "Nicklas",
    lastName: "Bruheim",
    address: "3687 Filips gate",
    city: "Brandal",
    state: "CT",
    zip: "7596",
    division: "Light heavyweight",
    boxerHeight: 1.78,
    boxerReach: 66.6,
    boxerWins: 13,
    boxerLoses: 0,
    couchName: "Felipe Bravo",
    email: "nicklas.bruheim@example.com",
    gymName: "Bravo Gym",
    licNum: "a5c2e393",
    userName: "crazywolf928",
    password: "defense",
    role: "Boxer",
    title: "none",
    phoneNumber: "37842466",
    picture: "https://randomuser.me/api/portraits/med/men/55.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/55.jpg",
  },
  {
    firstName: "Hector",
    lastName: "Thomas",
    address: "7838 Wycliff Ave",
    city: "Melbourne",
    state: "CT",
    zip: "2582",
    division: "Welterweight",
    boxerHeight: 1.8,
    boxerReach: 71.2,
    boxerWins: 17,
    boxerLoses: 1,
    couchName: "Daniel Saari",
    email: "hector.thomas@example.com",
    gymName: "Danielo Gym",
    licNum: "7d2a408e",
    userName: "organicwolf749",
    password: "otto",
    role: "Boxer",
    title: "none",
    phoneNumber: "01-9705-7881",
    picture: "https://randomuser.me/api/portraits/med/men/13.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/13.jpg",
  },
  {
    firstName: "Elijah",
    lastName: "Thomas",
    address: "4295 Mahia Road",
    city: "New Plymouth",
    state: "CT",
    zip: "43816",
    division: "Welterweight",
    boxerHeight: 1.74,
    boxerReach: 69.5,
    boxerWins: 29,
    boxerLoses: 6,
    couchName: "Daniel Saari",
    email: "elijah.thomas@example.com",
    gymName: "Danielo Gym",
    licNum: "0232ec1d",
    userName: "blacksnake567",
    password: "5000",
    role: "Boxer",
    title: "none",
    phoneNumber: "(488)-730-5151",
    picture: "https://randomuser.me/api/portraits/med/men/34.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/34.jpg",
  },
  {
    firstName: "Terrance",
    lastName: "Schmidt",
    address: "4518 Richmond Road",
    city: "Cardiff",
    state: "CT",
    zip: "B7 0AB",
    division: "Welterweight",
    boxerHeight: 1.87,
    boxerReach: 64.8,
    boxerWins: 2,
    boxerLoses: 0,
    couchName: "Daniel Saari",
    email: "terrance.schmidt@example.com",
    gymName: "Danielo Gym",
    licNum: "d487dc65",
    userName: "smallswan982",
    password: "jeannie",
    role: "Boxer",
    title: "Welterweight Champion",
    phoneNumber: "016977 66187",
    picture: "https://randomuser.me/api/portraits/med/men/41.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/41.jpg",
  },
  {
    firstName: "Tim",
    lastName: "Sullivan",
    address: "2779 Church Street",
    city: "Wicklow",
    state: "CT",
    zip: "84535",
    division: "Welterweight",
    boxerHeight: 1.74,
    boxerReach: 64.5,
    boxerWins: 41,
    boxerLoses: 13,
    couchName: "Daniel Saari",
    email: "tim.sullivan@example.com",
    gymName: "Danielo Gym",
    licNum: "dce7dbfb",
    userName: "lazylion354",
    password: "bounce",
    role: "Boxer",
    title: "none",
    phoneNumber: "031-901-7482",
    picture: "https://randomuser.me/api/portraits/med/men/81.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/81.jpg",
  },
  {
    firstName: "Ricardo",
    lastName: "Iglesias",
    address: "6314 Calle de La Almudena",
    city: "Vigo",
    state: "CT",
    zip: "17714",
    division: "Welterweight",
    boxerHeight: 1.74,
    boxerReach: 69.5,
    boxerWins: 18,
    boxerLoses: 0,
    couchName: "Daniel Saari",
    email: "ricardo.iglesias@example.com",
    gymName: "Danielo Gym",
    licNum: "46877660",
    userName: "greenmeercat583",
    password: "backup",
    role: "Boxer",
    title: "none",
    phoneNumber: "906-488-352",
    picture: "https://randomuser.me/api/portraits/med/men/25.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
  },
  {
    firstName: "Gary",
    lastName: "Bowman",
    address: "7680 High Street",
    city: "Dundalk",
    state: "CT",
    zip: "89159",
    division: "Welterweight",
    boxerHeight: 1.45,
    boxerReach: 62.8,
    boxerWins: 22,
    boxerLoses: 2,
    couchName: "Willy Gärtner",
    email: "gary.bowman@example.com",
    gymName: "The Best Gym",
    licNum: "0708e50a",
    userName: "redzebra506",
    password: "jughead",
    role: "Boxer",
    title: "none",
    phoneNumber: "041-869-3229",
    picture: "https://randomuser.me/api/portraits/med/men/51.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/51.jpg",
  },
  {
    firstName: "Anton",
    lastName: "Christiansen",
    address: "4705 Solbakkevej",
    city: "Hornbæk",
    state: "CT",
    zip: "66513",
    division: "Welterweight",
    boxerHeight: 1.72,
    boxerReach: 69.7,
    boxerWins: 24,
    boxerLoses: 0,
    couchName: "Willy Gärtner",
    email: "anton.christiansen@example.com",
    gymName: "The Best Gym",
    licNum: "0d675bff",
    userName: "whitezebra275",
    password: "malaka",
    role: "Boxer",
    title: "none",
    phoneNumber: "80386638",
    picture: "https://randomuser.me/api/portraits/med/men/90.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/90.jpg",
  },
  {
    firstName: "Raymond",
    lastName: "Dunn",
    address: "3518 The Green",
    city: "Winchester",
    state: "CT",
    zip: "SL29 0WY",
    division: "Welterweight",
    boxerHeight: 1.84,
    boxerReach: 71.2,
    boxerWins: 24,
    boxerLoses: 4,
    couchName: "Willy Gärtner",
    email: "raymond.dunn@example.com",
    gymName: "The Best Gym",
    licNum: "f682a16e",
    userName: "redwolf684",
    password: "japan",
    role: "Boxer",
    title: "none",
    phoneNumber: "0114712 377 5694",
    picture: "https://randomuser.me/api/portraits/med/men/93.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/93.jpg",
  },
  {
    firstName: "Ian",
    lastName: "Vasquez",
    address: "96 W Sherman Dr",
    city: "Fresno",
    state: "CT",
    zip: "93217",
    division: "Welterweight",
    boxerHeight: 1.9,
    boxerReach: 68.9,
    boxerWins: 28,
    boxerLoses: 6,
    couchName: "Willy Gärtner",
    email: "ian.vasquez@example.com",
    gymName: "The Best Gym",
    licNum: "77610c43",
    userName: "greensnake490",
    password: "wert",
    role: "Boxer",
    title: "Welterweight Champion",
    phoneNumber: "(856)-019-0734",
    picture: "https://randomuser.me/api/portraits/med/men/54.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/54.jpg",
  },
  {
    firstName: "Anthony",
    lastName: "Legrand",
    address: "6692 Rue D'Abbeville",
    city: "Angers",
    state: "CT",
    zip: "42750",
    division: "Welterweight",
    boxerHeight: 1.41,
    boxerReach: 56.4,
    boxerWins: 38,
    boxerLoses: 2,
    couchName: "Willy Gärtner",
    email: "anthony.legrand@example.com",
    gymName: "The Best Gym",
    licNum: "6f51a75b",
    userName: "beautifulfrog618",
    password: "bama",
    role: "Boxer",
    title: "Welterweight Champion",
    phoneNumber: "04-62-24-25-74",
    picture: "https://randomuser.me/api/portraits/med/men/78.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/78.jpg",
  },
  {
    firstName: "Ragnar",
    lastName: "Bråthen",
    address: "1531 Ustvedts vei",
    city: "Tranby",
    state: "CT",
    zip: "1201",
    division: "Light welterweight",
    boxerHeight: 1.45,
    boxerReach: 56.9,
    boxerWins: 18,
    boxerLoses: 2,
    couchName: "Willy Gärtner",
    email: "ragnar.brathen@example.com",
    gymName: "The Best Gym",
    licNum: "3d186137",
    userName: "silverfish869",
    password: "space",
    role: "Boxer",
    title: "none",
    phoneNumber: "63793033",
    picture: "https://randomuser.me/api/portraits/med/men/13.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/13.jpg",
  },
  {
    firstName: "Matthew",
    lastName: "Lo",
    address: "9230 Coastal Highway",
    city: "Glenwood",
    state: "CT",
    zip: "A8D 9A5",
    division: "Light welterweight",
    boxerHeight: 1.8,
    boxerReach: 67.8,
    boxerWins: 8,
    boxerLoses: 0,
    couchName: "Willy Gärtner",
    email: "matthew.lo@example.com",
    gymName: "The Best Gym",
    licNum: "86e54050",
    userName: "beautifulrabbit631",
    password: "hentai",
    role: "Boxer",
    title: "none",
    phoneNumber: "916-406-0025",
    picture: "https://randomuser.me/api/portraits/med/men/53.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
  },
  {
    firstName: "Snorre",
    lastName: "Valseth",
    address: "5320 Myrerdraget",
    city: "Vossevangen",
    state: "CT",
    zip: "5334",
    division: "Light welterweight",
    boxerHeight: 1.85,
    boxerReach: 69.7,
    boxerWins: 6,
    boxerLoses: 1,
    couchName: "Willy Gärtner",
    email: "snorre.valseth@example.com",
    gymName: "The Best Gym",
    licNum: "e8654300",
    userName: "tinymeercat441",
    password: "blacky",
    role: "Boxer",
    title: "none",
    phoneNumber: "69286263",
    picture: "https://randomuser.me/api/portraits/med/men/11.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
  },
  {
    firstName: "Timmothy",
    lastName: "Woods",
    address: "1539 Green Lane",
    city: "Armagh",
    state: "CT",
    zip: "B0Z 0TD",
    division: "Light welterweight",
    boxerHeight: 1.79,
    boxerReach: 68.8,
    boxerWins: 2,
    boxerLoses: 0,
    couchName: "Willy Gärtner",
    email: "timmothy.woods@example.com",
    gymName: "The Best Gym",
    licNum: "2bfb3fb7",
    userName: "bigbutterfly949",
    password: "oscar",
    role: "Boxer",
    title: "none",
    phoneNumber: "015242 61536",
    picture: "https://randomuser.me/api/portraits/med/men/61.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/61.jpg",
  },
  {
    firstName: "Édouard",
    lastName: "Berger",
    address: "9838 Place de L'Abbé-Basset",
    city: "Illgau",
    state: "CT",
    zip: "2483",
    division: "Light welterweight",
    boxerHeight: 1.94,
    boxerReach: 71.2,
    boxerWins: 20,
    boxerLoses: 1,
    couchName: "Willy Gärtner",
    email: "edouard.berger@example.com",
    gymName: "The Best Gym",
    licNum: "0f878669",
    userName: "greengoose712",
    password: "animated",
    role: "Boxer",
    title: "none",
    phoneNumber: "079 543 70 65",
    picture: "https://randomuser.me/api/portraits/med/men/46.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/46.jpg",
  },
  {
    firstName: "Remmert",
    lastName: "Hoedeman",
    address: "5598 Ganzenbeemd",
    city: "Wijdenes",
    state: "CT",
    zip: "21726",
    division: "Light welterweight",
    boxerHeight: "1.74",
    boxerReach: 59.9,
    boxerWins: 21,
    boxerLoses: 4,
    couchName: "Silas Jensen",
    email: "remmert.hoedeman@example.com",
    gymName: "Silas Gym",
    licNum: "b41ec87a",
    userName: "yellowcat317",
    password: "castle",
    role: "Boxer",
    title: "none",
    phoneNumber: "(251)-948-5217",
    picture: "https://randomuser.me/api/portraits/med/men/25.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
  },
  {
    firstName: "Otfried",
    lastName: "Döll",
    address: "4021 Am Sportplatz",
    city: "Leipheim",
    state: "CT",
    zip: "14627",
    division: "Light welterweight",
    boxerHeight: 1.87,
    boxerReach: 59.4,
    boxerWins: 24,
    boxerLoses: 5,
    couchName: "Silas Jensen",
    email: "otfried.doll@example.com",
    gymName: "Silas Gym",
    licNum: "0277b613",
    userName: "angrymouse451",
    password: "amanda1",
    role: "Boxer",
    title: "none",
    phoneNumber: "0288-0692071",
    picture: "https://randomuser.me/api/portraits/med/men/73.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/73.jpg",
  },
  {
    firstName: "Javier",
    lastName: "Serrano",
    address: "4345 Calle de Tetuán",
    city: "Albacete",
    state: "CT",
    zip: "65454",
    division: "Light welterweight",
    boxerHeight: 1.8,
    boxerReach: 62.8,
    boxerWins: 21,
    boxerLoses: 3,
    couchName: "Silas Jensen",
    email: "javier.serrano@example.com",
    gymName: "Silas Gym",
    licNum: "6fa695d6",
    userName: "greenbear897",
    password: "jester",
    role: "Boxer",
    title: "none",
    phoneNumber: "978-520-638",
    picture: "https://randomuser.me/api/portraits/med/men/44.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/44.jpg",
  },
  {
    firstName: "Theo",
    lastName: "Jackson",
    address: "7677 Customs Street",
    city: "Wellington",
    state: "CT",
    zip: "70210",
    division: "Light welterweight",
    boxerHeight: 1.79,
    boxerReach: 68.5,
    boxerWins: 10,
    boxerLoses: 0,
    couchName: "Silas Jensen",
    email: "theo.jackson@example.com",
    gymName: "Silas Gym",
    licNum: "56d2a6b7",
    userName: "blueduck691",
    password: "iceman",
    role: "Boxer",
    title: "none",
    phoneNumber: "(177)-420-2028",
    picture: "https://randomuser.me/api/portraits/med/men/63.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/63.jpg",
  },
  {
    firstName: "Don",
    lastName: "Carr",
    address: "7436 North Road",
    city: "Brighton and Hove",
    state: "CT",
    zip: "HF3Y 4JN",
    division: "",
    boxerHeight: 0,
    boxerReach: 0,
    boxerWins: 0,
    boxerLoses: 0,
    couchName: "",
    email: "don.carr@example.com",
    gymName: "",
    licNum: "",
    userName: "silvermouse367",
    password: "wilson",
    role: "User",
    title: "",
    phoneNumber: "016973 90906",
    picture: "https://randomuser.me/api/portraits/med/men/59.jpg",
    thumbnail: "https://randomuser.me/api/portraits/thumb/men/59.jpg",
  }
];

db.User.deleteMany({})
  .then(() => db.User.collection.insertMany(userSeed))
  .then((data) => {
    console.log(data.result.n + " records inserted");
    process.exit(0);
  })
  .catch((err) => {
    console.log(err);
    process.exit(1);
  });
